apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: bb-cc
  labels:
    app: bb
data:
  default.conf: |
    upstream bb_project {
        server bb-service:8080;
    }
    server {

        listen 80;

        location / {
            proxy_pass http://bb_project;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }
