apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bb-cc
  labels:
    app: bb
spec:
  type: NodePort
  selector:
    app: bb-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
