apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-deployment
  namespace: bb-cc
  labels:
    app: bb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-app
  template:
    metadata:
      labels:
        app: bb-app
    spec:
      containers:
        - image: jlacerdatng10/express
          imagePullPolicy: Never
          name: sample-container
          ports:
            - containerPort: 8080
              name: express
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
